insert into clubRole values ('speaker1','First Speech');
insert into clubRole values ('speaker2', 'Second Speech');
insert into clubRole values ('tableTopics','Table Topics');
insert into clubRole values ('toastMaster',   'Toast Master');
insert into clubRole values ('generalEvaluator',   'General Evaluator');
insert into clubRole values ('evaluator1',   'Evaluator for First Speech');
insert into clubRole values ('evaluator2',   'Evaluator for Second Speech');
insert into clubRole values ('grammarian',   'Grammarian');
insert into clubRole values ('timer',   'Timer');
insert into clubRole values ('ttResponse1',   'Table Topic Response1');
insert into clubRole values ('ttResponse2',   'Table Topic Response2');
insert into clubRole values ('ttResponse3',   'Table Topic Response3');
insert into clubRole values ('ttResponse4',   'Table Topic Response4');
insert into clubRole values ('ttResponse5',   'Table Topic Response5');
insert into clubRole values ('ttResponse6',   'Table Topic Response6');
insert into clubRole values ('ttResponse7',   'Table Topic Response7');
insert into clubRole values ('ttResponse',    'Table Topic Response8');
